/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsFormIndexRouteImport } from './routes/docs/form/index'
import { Route as DocsFormAnatomyRouteImport } from './routes/docs/form/anatomy'
import { Route as DocsFormConfigurationRouteImport } from './routes/docs/form/configuration'
import { Route as DocsFormControllersRouteImport } from './routes/docs/form/controllers'
import { Route as DocsFormCustomControllerRouteImport } from './routes/docs/form/custom-controller'
import { Route as DocsFormFieldsRouteImport } from './routes/docs/form/fields'
import { Route as DocsFormGroupsRouteImport } from './routes/docs/form/groups'
import { Route as DocsFormInstallationRouteImport } from './routes/docs/form/installation'
import { Route as DocsFormNestedRouteImport } from './routes/docs/form/nested'
import { Route as DocsFormRegistryRouteImport } from './routes/docs/form/registry'
import { Route as DocsFormStepsRouteImport } from './routes/docs/form/steps'
import { Route as DocsFormValidationRouteImport } from './routes/docs/form/validation'
import { Route as DocsResourceViewIndexRouteImport } from './routes/docs/resource-view/index'
import { Route as DocsResourceViewBackendsRouteImport } from './routes/docs/resource-view/backends'
import { Route as DocsResourceViewCalendarRouteImport } from './routes/docs/resource-view/calendar'
import { Route as DocsResourceViewCustomVariantRouteImport } from './routes/docs/resource-view/custom-variant'
import { Route as DocsResourceViewFiltersRouteImport } from './routes/docs/resource-view/filters'
import { Route as DocsResourceViewInstallationRouteImport } from './routes/docs/resource-view/installation'
import { Route as DocsResourceViewLayoutsRouteImport } from './routes/docs/resource-view/layouts'
import { Route as DocsResourceViewPermissionsRouteImport } from './routes/docs/resource-view/permissions'
import { Route as DocsResourceViewResourcesRouteImport } from './routes/docs/resource-view/resources'
import { Route as DocsResourceViewRoutingRouteImport } from './routes/docs/resource-view/routing'
import { Route as DocsResourceViewScopesRouteImport } from './routes/docs/resource-view/scopes'
import { Route as DocsResourceViewSplitRouteImport } from './routes/docs/resource-view/split'
import { Route as DocsResourceViewSubViewsRouteImport } from './routes/docs/resource-view/sub-views'
import { Route as DocsResourceViewTableRouteImport } from './routes/docs/resource-view/table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormIndexRoute = DocsFormIndexRouteImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormAnatomyRoute = DocsFormAnatomyRouteImport.update({
  id: '/form/anatomy',
  path: '/form/anatomy',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormConfigurationRoute = DocsFormConfigurationRouteImport.update({
  id: '/form/configuration',
  path: '/form/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormControllersRoute = DocsFormControllersRouteImport.update({
  id: '/form/controllers',
  path: '/form/controllers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormCustomControllerRoute =
  DocsFormCustomControllerRouteImport.update({
    id: '/form/custom-controller',
    path: '/form/custom-controller',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsFormFieldsRoute = DocsFormFieldsRouteImport.update({
  id: '/form/fields',
  path: '/form/fields',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormGroupsRoute = DocsFormGroupsRouteImport.update({
  id: '/form/groups',
  path: '/form/groups',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormInstallationRoute = DocsFormInstallationRouteImport.update({
  id: '/form/installation',
  path: '/form/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormNestedRoute = DocsFormNestedRouteImport.update({
  id: '/form/nested',
  path: '/form/nested',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormRegistryRoute = DocsFormRegistryRouteImport.update({
  id: '/form/registry',
  path: '/form/registry',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormStepsRoute = DocsFormStepsRouteImport.update({
  id: '/form/steps',
  path: '/form/steps',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormValidationRoute = DocsFormValidationRouteImport.update({
  id: '/form/validation',
  path: '/form/validation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewIndexRoute = DocsResourceViewIndexRouteImport.update({
  id: '/resource-view/',
  path: '/resource-view/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewBackendsRoute =
  DocsResourceViewBackendsRouteImport.update({
    id: '/resource-view/backends',
    path: '/resource-view/backends',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewCalendarRoute =
  DocsResourceViewCalendarRouteImport.update({
    id: '/resource-view/calendar',
    path: '/resource-view/calendar',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewCustomVariantRoute =
  DocsResourceViewCustomVariantRouteImport.update({
    id: '/resource-view/custom-variant',
    path: '/resource-view/custom-variant',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewFiltersRoute = DocsResourceViewFiltersRouteImport.update({
  id: '/resource-view/filters',
  path: '/resource-view/filters',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewInstallationRoute =
  DocsResourceViewInstallationRouteImport.update({
    id: '/resource-view/installation',
    path: '/resource-view/installation',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewLayoutsRoute = DocsResourceViewLayoutsRouteImport.update({
  id: '/resource-view/layouts',
  path: '/resource-view/layouts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewPermissionsRoute =
  DocsResourceViewPermissionsRouteImport.update({
    id: '/resource-view/permissions',
    path: '/resource-view/permissions',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewResourcesRoute =
  DocsResourceViewResourcesRouteImport.update({
    id: '/resource-view/resources',
    path: '/resource-view/resources',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewRoutingRoute = DocsResourceViewRoutingRouteImport.update({
  id: '/resource-view/routing',
  path: '/resource-view/routing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewScopesRoute = DocsResourceViewScopesRouteImport.update({
  id: '/resource-view/scopes',
  path: '/resource-view/scopes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewSplitRoute = DocsResourceViewSplitRouteImport.update({
  id: '/resource-view/split',
  path: '/resource-view/split',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResourceViewSubViewsRoute =
  DocsResourceViewSubViewsRouteImport.update({
    id: '/resource-view/sub-views',
    path: '/resource-view/sub-views',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsResourceViewTableRoute = DocsResourceViewTableRouteImport.update({
  id: '/resource-view/table',
  path: '/resource-view/table',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/form/anatomy': typeof DocsFormAnatomyRoute
  '/docs/form/configuration': typeof DocsFormConfigurationRoute
  '/docs/form/controllers': typeof DocsFormControllersRoute
  '/docs/form/custom-controller': typeof DocsFormCustomControllerRoute
  '/docs/form/fields': typeof DocsFormFieldsRoute
  '/docs/form/groups': typeof DocsFormGroupsRoute
  '/docs/form/installation': typeof DocsFormInstallationRoute
  '/docs/form/nested': typeof DocsFormNestedRoute
  '/docs/form/registry': typeof DocsFormRegistryRoute
  '/docs/form/steps': typeof DocsFormStepsRoute
  '/docs/form/validation': typeof DocsFormValidationRoute
  '/docs/resource-view/backends': typeof DocsResourceViewBackendsRoute
  '/docs/resource-view/calendar': typeof DocsResourceViewCalendarRoute
  '/docs/resource-view/custom-variant': typeof DocsResourceViewCustomVariantRoute
  '/docs/resource-view/filters': typeof DocsResourceViewFiltersRoute
  '/docs/resource-view/installation': typeof DocsResourceViewInstallationRoute
  '/docs/resource-view/layouts': typeof DocsResourceViewLayoutsRoute
  '/docs/resource-view/permissions': typeof DocsResourceViewPermissionsRoute
  '/docs/resource-view/resources': typeof DocsResourceViewResourcesRoute
  '/docs/resource-view/routing': typeof DocsResourceViewRoutingRoute
  '/docs/resource-view/scopes': typeof DocsResourceViewScopesRoute
  '/docs/resource-view/split': typeof DocsResourceViewSplitRoute
  '/docs/resource-view/sub-views': typeof DocsResourceViewSubViewsRoute
  '/docs/resource-view/table': typeof DocsResourceViewTableRoute
  '/docs/form/': typeof DocsFormIndexRoute
  '/docs/resource-view/': typeof DocsResourceViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/docs': typeof DocsIndexRoute
  '/docs/form/anatomy': typeof DocsFormAnatomyRoute
  '/docs/form/configuration': typeof DocsFormConfigurationRoute
  '/docs/form/controllers': typeof DocsFormControllersRoute
  '/docs/form/custom-controller': typeof DocsFormCustomControllerRoute
  '/docs/form/fields': typeof DocsFormFieldsRoute
  '/docs/form/groups': typeof DocsFormGroupsRoute
  '/docs/form/installation': typeof DocsFormInstallationRoute
  '/docs/form/nested': typeof DocsFormNestedRoute
  '/docs/form/registry': typeof DocsFormRegistryRoute
  '/docs/form/steps': typeof DocsFormStepsRoute
  '/docs/form/validation': typeof DocsFormValidationRoute
  '/docs/resource-view/backends': typeof DocsResourceViewBackendsRoute
  '/docs/resource-view/calendar': typeof DocsResourceViewCalendarRoute
  '/docs/resource-view/custom-variant': typeof DocsResourceViewCustomVariantRoute
  '/docs/resource-view/filters': typeof DocsResourceViewFiltersRoute
  '/docs/resource-view/installation': typeof DocsResourceViewInstallationRoute
  '/docs/resource-view/layouts': typeof DocsResourceViewLayoutsRoute
  '/docs/resource-view/permissions': typeof DocsResourceViewPermissionsRoute
  '/docs/resource-view/resources': typeof DocsResourceViewResourcesRoute
  '/docs/resource-view/routing': typeof DocsResourceViewRoutingRoute
  '/docs/resource-view/scopes': typeof DocsResourceViewScopesRoute
  '/docs/resource-view/split': typeof DocsResourceViewSplitRoute
  '/docs/resource-view/sub-views': typeof DocsResourceViewSubViewsRoute
  '/docs/resource-view/table': typeof DocsResourceViewTableRoute
  '/docs/form': typeof DocsFormIndexRoute
  '/docs/resource-view': typeof DocsResourceViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/form/anatomy': typeof DocsFormAnatomyRoute
  '/docs/form/configuration': typeof DocsFormConfigurationRoute
  '/docs/form/controllers': typeof DocsFormControllersRoute
  '/docs/form/custom-controller': typeof DocsFormCustomControllerRoute
  '/docs/form/fields': typeof DocsFormFieldsRoute
  '/docs/form/groups': typeof DocsFormGroupsRoute
  '/docs/form/installation': typeof DocsFormInstallationRoute
  '/docs/form/nested': typeof DocsFormNestedRoute
  '/docs/form/registry': typeof DocsFormRegistryRoute
  '/docs/form/steps': typeof DocsFormStepsRoute
  '/docs/form/validation': typeof DocsFormValidationRoute
  '/docs/resource-view/backends': typeof DocsResourceViewBackendsRoute
  '/docs/resource-view/calendar': typeof DocsResourceViewCalendarRoute
  '/docs/resource-view/custom-variant': typeof DocsResourceViewCustomVariantRoute
  '/docs/resource-view/filters': typeof DocsResourceViewFiltersRoute
  '/docs/resource-view/installation': typeof DocsResourceViewInstallationRoute
  '/docs/resource-view/layouts': typeof DocsResourceViewLayoutsRoute
  '/docs/resource-view/permissions': typeof DocsResourceViewPermissionsRoute
  '/docs/resource-view/resources': typeof DocsResourceViewResourcesRoute
  '/docs/resource-view/routing': typeof DocsResourceViewRoutingRoute
  '/docs/resource-view/scopes': typeof DocsResourceViewScopesRoute
  '/docs/resource-view/split': typeof DocsResourceViewSplitRoute
  '/docs/resource-view/sub-views': typeof DocsResourceViewSubViewsRoute
  '/docs/resource-view/table': typeof DocsResourceViewTableRoute
  '/docs/form/': typeof DocsFormIndexRoute
  '/docs/resource-view/': typeof DocsResourceViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/docs/'
    | '/docs/form/anatomy'
    | '/docs/form/configuration'
    | '/docs/form/controllers'
    | '/docs/form/custom-controller'
    | '/docs/form/fields'
    | '/docs/form/groups'
    | '/docs/form/installation'
    | '/docs/form/nested'
    | '/docs/form/registry'
    | '/docs/form/steps'
    | '/docs/form/validation'
    | '/docs/resource-view/backends'
    | '/docs/resource-view/calendar'
    | '/docs/resource-view/custom-variant'
    | '/docs/resource-view/filters'
    | '/docs/resource-view/installation'
    | '/docs/resource-view/layouts'
    | '/docs/resource-view/permissions'
    | '/docs/resource-view/resources'
    | '/docs/resource-view/routing'
    | '/docs/resource-view/scopes'
    | '/docs/resource-view/split'
    | '/docs/resource-view/sub-views'
    | '/docs/resource-view/table'
    | '/docs/form/'
    | '/docs/resource-view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/docs'
    | '/docs/form/anatomy'
    | '/docs/form/configuration'
    | '/docs/form/controllers'
    | '/docs/form/custom-controller'
    | '/docs/form/fields'
    | '/docs/form/groups'
    | '/docs/form/installation'
    | '/docs/form/nested'
    | '/docs/form/registry'
    | '/docs/form/steps'
    | '/docs/form/validation'
    | '/docs/resource-view/backends'
    | '/docs/resource-view/calendar'
    | '/docs/resource-view/custom-variant'
    | '/docs/resource-view/filters'
    | '/docs/resource-view/installation'
    | '/docs/resource-view/layouts'
    | '/docs/resource-view/permissions'
    | '/docs/resource-view/resources'
    | '/docs/resource-view/routing'
    | '/docs/resource-view/scopes'
    | '/docs/resource-view/split'
    | '/docs/resource-view/sub-views'
    | '/docs/resource-view/table'
    | '/docs/form'
    | '/docs/resource-view'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/docs/'
    | '/docs/form/anatomy'
    | '/docs/form/configuration'
    | '/docs/form/controllers'
    | '/docs/form/custom-controller'
    | '/docs/form/fields'
    | '/docs/form/groups'
    | '/docs/form/installation'
    | '/docs/form/nested'
    | '/docs/form/registry'
    | '/docs/form/steps'
    | '/docs/form/validation'
    | '/docs/resource-view/backends'
    | '/docs/resource-view/calendar'
    | '/docs/resource-view/custom-variant'
    | '/docs/resource-view/filters'
    | '/docs/resource-view/installation'
    | '/docs/resource-view/layouts'
    | '/docs/resource-view/permissions'
    | '/docs/resource-view/resources'
    | '/docs/resource-view/routing'
    | '/docs/resource-view/scopes'
    | '/docs/resource-view/split'
    | '/docs/resource-view/sub-views'
    | '/docs/resource-view/table'
    | '/docs/form/'
    | '/docs/resource-view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/': {
      id: '/docs/form/'
      path: '/form'
      fullPath: '/docs/form/'
      preLoaderRoute: typeof DocsFormIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/anatomy': {
      id: '/docs/form/anatomy'
      path: '/form/anatomy'
      fullPath: '/docs/form/anatomy'
      preLoaderRoute: typeof DocsFormAnatomyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/configuration': {
      id: '/docs/form/configuration'
      path: '/form/configuration'
      fullPath: '/docs/form/configuration'
      preLoaderRoute: typeof DocsFormConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/controllers': {
      id: '/docs/form/controllers'
      path: '/form/controllers'
      fullPath: '/docs/form/controllers'
      preLoaderRoute: typeof DocsFormControllersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/custom-controller': {
      id: '/docs/form/custom-controller'
      path: '/form/custom-controller'
      fullPath: '/docs/form/custom-controller'
      preLoaderRoute: typeof DocsFormCustomControllerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/fields': {
      id: '/docs/form/fields'
      path: '/form/fields'
      fullPath: '/docs/form/fields'
      preLoaderRoute: typeof DocsFormFieldsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/groups': {
      id: '/docs/form/groups'
      path: '/form/groups'
      fullPath: '/docs/form/groups'
      preLoaderRoute: typeof DocsFormGroupsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/installation': {
      id: '/docs/form/installation'
      path: '/form/installation'
      fullPath: '/docs/form/installation'
      preLoaderRoute: typeof DocsFormInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/nested': {
      id: '/docs/form/nested'
      path: '/form/nested'
      fullPath: '/docs/form/nested'
      preLoaderRoute: typeof DocsFormNestedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/registry': {
      id: '/docs/form/registry'
      path: '/form/registry'
      fullPath: '/docs/form/registry'
      preLoaderRoute: typeof DocsFormRegistryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/steps': {
      id: '/docs/form/steps'
      path: '/form/steps'
      fullPath: '/docs/form/steps'
      preLoaderRoute: typeof DocsFormStepsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/form/validation': {
      id: '/docs/form/validation'
      path: '/form/validation'
      fullPath: '/docs/form/validation'
      preLoaderRoute: typeof DocsFormValidationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/': {
      id: '/docs/resource-view/'
      path: '/resource-view'
      fullPath: '/docs/resource-view/'
      preLoaderRoute: typeof DocsResourceViewIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/backends': {
      id: '/docs/resource-view/backends'
      path: '/resource-view/backends'
      fullPath: '/docs/resource-view/backends'
      preLoaderRoute: typeof DocsResourceViewBackendsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/calendar': {
      id: '/docs/resource-view/calendar'
      path: '/resource-view/calendar'
      fullPath: '/docs/resource-view/calendar'
      preLoaderRoute: typeof DocsResourceViewCalendarRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/custom-variant': {
      id: '/docs/resource-view/custom-variant'
      path: '/resource-view/custom-variant'
      fullPath: '/docs/resource-view/custom-variant'
      preLoaderRoute: typeof DocsResourceViewCustomVariantRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/filters': {
      id: '/docs/resource-view/filters'
      path: '/resource-view/filters'
      fullPath: '/docs/resource-view/filters'
      preLoaderRoute: typeof DocsResourceViewFiltersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/installation': {
      id: '/docs/resource-view/installation'
      path: '/resource-view/installation'
      fullPath: '/docs/resource-view/installation'
      preLoaderRoute: typeof DocsResourceViewInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/layouts': {
      id: '/docs/resource-view/layouts'
      path: '/resource-view/layouts'
      fullPath: '/docs/resource-view/layouts'
      preLoaderRoute: typeof DocsResourceViewLayoutsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/permissions': {
      id: '/docs/resource-view/permissions'
      path: '/resource-view/permissions'
      fullPath: '/docs/resource-view/permissions'
      preLoaderRoute: typeof DocsResourceViewPermissionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/resources': {
      id: '/docs/resource-view/resources'
      path: '/resource-view/resources'
      fullPath: '/docs/resource-view/resources'
      preLoaderRoute: typeof DocsResourceViewResourcesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/routing': {
      id: '/docs/resource-view/routing'
      path: '/resource-view/routing'
      fullPath: '/docs/resource-view/routing'
      preLoaderRoute: typeof DocsResourceViewRoutingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/scopes': {
      id: '/docs/resource-view/scopes'
      path: '/resource-view/scopes'
      fullPath: '/docs/resource-view/scopes'
      preLoaderRoute: typeof DocsResourceViewScopesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/split': {
      id: '/docs/resource-view/split'
      path: '/resource-view/split'
      fullPath: '/docs/resource-view/split'
      preLoaderRoute: typeof DocsResourceViewSplitRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/sub-views': {
      id: '/docs/resource-view/sub-views'
      path: '/resource-view/sub-views'
      fullPath: '/docs/resource-view/sub-views'
      preLoaderRoute: typeof DocsResourceViewSubViewsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resource-view/table': {
      id: '/docs/resource-view/table'
      path: '/resource-view/table'
      fullPath: '/docs/resource-view/table'
      preLoaderRoute: typeof DocsResourceViewTableRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsFormAnatomyRoute: typeof DocsFormAnatomyRoute
  DocsFormConfigurationRoute: typeof DocsFormConfigurationRoute
  DocsFormControllersRoute: typeof DocsFormControllersRoute
  DocsFormCustomControllerRoute: typeof DocsFormCustomControllerRoute
  DocsFormFieldsRoute: typeof DocsFormFieldsRoute
  DocsFormGroupsRoute: typeof DocsFormGroupsRoute
  DocsFormInstallationRoute: typeof DocsFormInstallationRoute
  DocsFormNestedRoute: typeof DocsFormNestedRoute
  DocsFormRegistryRoute: typeof DocsFormRegistryRoute
  DocsFormStepsRoute: typeof DocsFormStepsRoute
  DocsFormValidationRoute: typeof DocsFormValidationRoute
  DocsResourceViewBackendsRoute: typeof DocsResourceViewBackendsRoute
  DocsResourceViewCalendarRoute: typeof DocsResourceViewCalendarRoute
  DocsResourceViewCustomVariantRoute: typeof DocsResourceViewCustomVariantRoute
  DocsResourceViewFiltersRoute: typeof DocsResourceViewFiltersRoute
  DocsResourceViewInstallationRoute: typeof DocsResourceViewInstallationRoute
  DocsResourceViewLayoutsRoute: typeof DocsResourceViewLayoutsRoute
  DocsResourceViewPermissionsRoute: typeof DocsResourceViewPermissionsRoute
  DocsResourceViewResourcesRoute: typeof DocsResourceViewResourcesRoute
  DocsResourceViewRoutingRoute: typeof DocsResourceViewRoutingRoute
  DocsResourceViewScopesRoute: typeof DocsResourceViewScopesRoute
  DocsResourceViewSplitRoute: typeof DocsResourceViewSplitRoute
  DocsResourceViewSubViewsRoute: typeof DocsResourceViewSubViewsRoute
  DocsResourceViewTableRoute: typeof DocsResourceViewTableRoute
  DocsFormIndexRoute: typeof DocsFormIndexRoute
  DocsResourceViewIndexRoute: typeof DocsResourceViewIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsFormAnatomyRoute: DocsFormAnatomyRoute,
  DocsFormConfigurationRoute: DocsFormConfigurationRoute,
  DocsFormControllersRoute: DocsFormControllersRoute,
  DocsFormCustomControllerRoute: DocsFormCustomControllerRoute,
  DocsFormFieldsRoute: DocsFormFieldsRoute,
  DocsFormGroupsRoute: DocsFormGroupsRoute,
  DocsFormInstallationRoute: DocsFormInstallationRoute,
  DocsFormNestedRoute: DocsFormNestedRoute,
  DocsFormRegistryRoute: DocsFormRegistryRoute,
  DocsFormStepsRoute: DocsFormStepsRoute,
  DocsFormValidationRoute: DocsFormValidationRoute,
  DocsResourceViewBackendsRoute: DocsResourceViewBackendsRoute,
  DocsResourceViewCalendarRoute: DocsResourceViewCalendarRoute,
  DocsResourceViewCustomVariantRoute: DocsResourceViewCustomVariantRoute,
  DocsResourceViewFiltersRoute: DocsResourceViewFiltersRoute,
  DocsResourceViewInstallationRoute: DocsResourceViewInstallationRoute,
  DocsResourceViewLayoutsRoute: DocsResourceViewLayoutsRoute,
  DocsResourceViewPermissionsRoute: DocsResourceViewPermissionsRoute,
  DocsResourceViewResourcesRoute: DocsResourceViewResourcesRoute,
  DocsResourceViewRoutingRoute: DocsResourceViewRoutingRoute,
  DocsResourceViewScopesRoute: DocsResourceViewScopesRoute,
  DocsResourceViewSplitRoute: DocsResourceViewSplitRoute,
  DocsResourceViewSubViewsRoute: DocsResourceViewSubViewsRoute,
  DocsResourceViewTableRoute: DocsResourceViewTableRoute,
  DocsFormIndexRoute: DocsFormIndexRoute,
  DocsResourceViewIndexRoute: DocsResourceViewIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
